#!/bin/sh

# Checksource run for all the files
echo Running checksource on all files...
echo

checksource cix.cpp
checksource cixd.cpp
checksource logstream.h
checksource Makefile
checksource protocol.cpp
checksource protocol.h
checksource README
checksource sockets.cpp
checksource sockets.h
checksource PARTNER

# cpplint.py.perl run
echo Running cpplint.py.perl on relevant files...
echo

cpplint.py.perl cix.cpp
cpplint.py.perl cixd.cpp
cpplint.py.perl logstream.h
cpplint.py.perl protocol.cpp
cpplint.py.perl protocol.h
cpplint.py.perl sockets.cpp
cpplint.py.perl sockets.h

# Partnercheck run
echo Running partnercheck...
echo

partnercheck

# submit
echo Submitting files...
echo

submit cmps109-wm.u18 asg4 cix.cpp cixd.cpp logstream.h Makefile \
protocol.cpp protocol.h README sockets.cpp sockets.h PARTNER
